"use strict";
/**
 * Created by Christophe on 06/03/2017.
 */
var sprite_class_1 = require("../src/core/display/sprite.class");
var file_class_1 = require("../src/core/files/file.class");
var events_class_1 = require("../src/core/common/events.class");
var control_class_1 = require("../src/core/gamelogic/control.class");
var control_sprite_class_1 = require("../src/core/display/control-sprite.class");
var sprites_group_class_1 = require("../src/core/display/sprites-group.class");
var sprites_group_state_class_1 = require("../src/core/display/sprites-group-state.class");
var trigger_class_1 = require("../src/core/triggers/trigger.class");
var graph_node_class_1 = require("../src/core/graphs/graph-node.class");
var graph_link_class_1 = require("../src/core/graphs/graph-link.class");
var graph_class_1 = require("../src/core/graphs/graph.class");
var time_trigger_class_1 = require("../src/core/triggers/time-trigger.class");
var status_class_1 = require("../src/core/common/status.class");
var p4 = new file_class_1.File("files/sprites/p4-body.png");
var p5 = new file_class_1.File("files/sprites/p5-body.png");
var p6 = new file_class_1.File("files/sprites/p6-body.png");
var p7 = new file_class_1.File("files/sprites/p7-body.png");
var crossControlFile = new file_class_1.File("files/controls/cross.png");
var controlAFile = new file_class_1.File("files/controls/buttonA.png");
var sprite1 = new sprite_class_1.Sprite(p4, 40, 100);
sprite1.displayInDOMElement(document.body);
var sprite2 = new sprite_class_1.Sprite(p5, 140, 100);
sprite2.displayInDOMElement(document.body);
var sprite3 = new sprite_class_1.Sprite(p6, 140, 200);
sprite3.displayInDOMElement(document.body);
var sprite4 = new sprite_class_1.Sprite(p7, 40, 200);
sprite4.displayInDOMElement(document.body);
var topSprite = new sprite_class_1.Sprite(p6, 90, 20);
topSprite.displayInDOMElement(document.body);
var group1 = new sprites_group_class_1.SpritesGroup([sprite1, sprite2, sprite3, sprite4, topSprite]);
var state1 = new sprites_group_state_class_1.SpritesGroupState(group1, [sprite1]);
var state2 = new sprites_group_state_class_1.SpritesGroupState(group1, [sprite2]);
var state3 = new sprites_group_state_class_1.SpritesGroupState(group1, [sprite3]);
var state4 = new sprites_group_state_class_1.SpritesGroupState(group1, [sprite4]);
var stateTop = new sprites_group_state_class_1.SpritesGroupState(group1, [topSprite]);
var crossControlSprite = new control_sprite_class_1.ControlSprite(crossControlFile, 350, 100);
crossControlSprite.displayInDOMElement(document.body);
var controlASprite = new control_sprite_class_1.ControlSprite(controlAFile, 480, 110);
controlASprite.displayInDOMElement(document.body);
var crossControlUp = new control_class_1.Control(crossControlSprite);
crossControlUp.setZone(28, 0, 28, 28);
var upTrigger = new trigger_class_1.Trigger(crossControlUp, events_class_1.Events.CONTROL_DOWN);
crossControlUp.enable();
var crossControlDown = new control_class_1.Control(crossControlSprite);
crossControlDown.setZone(28, 57, 28, 28);
var downTrigger = new trigger_class_1.Trigger(crossControlDown, events_class_1.Events.CONTROL_DOWN);
crossControlDown.enable();
var crossControlRight = new control_class_1.Control(crossControlSprite);
crossControlRight.setZone(56, 28, 28, 28);
var rightTrigger = new trigger_class_1.Trigger(crossControlRight, events_class_1.Events.CONTROL_DOWN);
crossControlRight.enable();
var crossControlLeft = new control_class_1.Control(crossControlSprite);
crossControlLeft.setZone(0, 28, 28, 28);
var leftTrigger = new trigger_class_1.Trigger(crossControlLeft, events_class_1.Events.CONTROL_DOWN);
crossControlLeft.enable();
var controlA = new control_class_1.Control(controlASprite);
var ATrigger = new trigger_class_1.Trigger(controlA, events_class_1.Events.CONTROL_DOWN);
controlA.enable();
var timeTrigger = new time_trigger_class_1.TimeTrigger(0.5);
var node1 = new graph_node_class_1.GraphNode(state1);
var node2 = new graph_node_class_1.GraphNode(state2);
var node3 = new graph_node_class_1.GraphNode(state3);
var node4 = new graph_node_class_1.GraphNode(state4);
var nodeTop = new graph_node_class_1.GraphNode(stateTop);
node1.addLink(new graph_link_class_1.GraphLink(node2, rightTrigger));
node1.addLink(new graph_link_class_1.GraphLink(node4, downTrigger));
node1.addLink(new graph_link_class_1.GraphLink(nodeTop, ATrigger));
nodeTop.addLink(new graph_link_class_1.GraphLink(node2, timeTrigger));
node2.addLink(new graph_link_class_1.GraphLink(node3, downTrigger));
node2.addLink(new graph_link_class_1.GraphLink(node1, leftTrigger));
node3.addLink(new graph_link_class_1.GraphLink(node2, upTrigger));
node3.addLink(new graph_link_class_1.GraphLink(node4, leftTrigger));
node4.addLink(new graph_link_class_1.GraphLink(node3, rightTrigger));
node4.addLink(new graph_link_class_1.GraphLink(node1, upTrigger));
var graph = new graph_class_1.Graph([node1, node2, node3, node4]);
graph.setNodeAsCurrent(node1);
sprite4.subscribe(status_class_1.Status.VISIBILITY, function (status) {
    //alert (status);
});
//# sourceMappingURL=graphs.js.map